// RSO data parsed from CSV
export const rsoData = [

  { name: "180 Degrees Consulting", description: "Pro bono consulting projects for nonprofits and social enterprises" },
  { name: "3484 Magazine", description: "Student-run magazine covering culture, arts, and current events" },
  { name: "3D Audio Lab at GT", description: "Exploring audio tech, wearables, and 3D printing" },
  { name: "5 Rivers Fishing Club", description: "Fly fishing community with trips and instruction" },
  { name: "A Cappella", description: "Student vocal performance groups" },
  { name: "ABLE Alliance", description: "Community-building and career support organization" },
  { name: "Academic Quizbowl Team", description: "Competitive trivia team" },
  { name: "Accessible Prosthetics Initiative", description: "Expands access to affordable prosthetics" },
  { name: "Acoustical Society of America", description: "Acoustics education and research outreach" },
  { name: "Aero Makers at GT", description: "Hands-on aerospace projects and mentoring" },
  { name: "Aerospace Design-Build-Fly Club", description: "Designs and flies RC aircraft competitively" },
  { name: "Agora", description: "Christian thought journal and forum" },
  { name: "AI Safety Initiative at GT", description: "Research and discussion on safe AI development" },
  { name: "AI@GT", description: "Artificial intelligence education and projects" },
  { name: "AIESEC", description: "International leadership and exchange programs" },
  { name: "Airsoft Club", description: "Recreational and competitive airsoft" },
  { name: "Amateur Radio Club", description: "Hands-on radio communication and licensing" },
  { name: "American Cancer Society @ GT", description: "Cancer awareness and fundraising" },
  { name: "American Concrete Institute", description: "Concrete industry education" },
  { name: "American Institute of Aeronautics & Astronautics", description: "Aerospace professional development" },
  { name: "American Institute of Architecture Students", description: "Architecture networking and advocacy" },
  { name: "American Medical Student Association", description: "Pre-health mentorship and advocacy" },
  { name: "American Nuclear Society", description: "Nuclear engineering education" },
  { name: "American Red Cross Club", description: "Disaster relief and blood drives" },
  { name: "American Sign Language Club", description: "Learning ASL and Deaf culture" },
  { name: "American Society of Civil Engineers", description: "Civil engineering professional org" },
  { name: "American Society of Mechanical Engineers", description: "Mechanical engineering professional org" },
  { name: "Animation Club", description: "Animation practice and workshops" },
  { name: "Anime O-Tekku", description: "Anime viewing and community" },
  { name: "Anti Brainrot Club", description: "Reducing doomscrolling and digital overuse" },
  { name: "Armwrestling @ GT", description: "Training and competition" },
  { name: "Art4Smiles", description: "Art outreach for underserved communities" },
  { name: "Astronomy Club", description: "Stargazing and astronomy education" },
  { name: "Audio Engineering Society @ GT", description: "Audio production education" },
  { name: "Badminton Club", description: "Recreational and competitive badminton" },
  { name: "Ballroom Dance Club", description: "Social and competitive ballroom dance" },
  { name: "Band Club", description: "Supports GT band programs" },
  { name: "Barbell Club", description: "Strength training community" },
  { name: "Beach Volleyball Club", description: "Competitive club volleyball" },
  { name: "Beekeeping", description: "Beekeeping education and hive care" },
  { name: "Big Data Big Impact", description: "Data science for social good" },
  { name: "Board Game Club", description: "Casual and competitive board games" },
  { name: "Boxing Club", description: "Training and competition" },
  { name: "Calisthenics at GT", description: "Bodyweight and gymnastics training" },
  { name: "Campus Cats", description: "Caring for feral cats on campus" },
  { name: "Chess Club", description: "Casual and tournament chess" },
  { name: "Climbing Club", description: "Indoor and outdoor climbing" },
  { name: "Club Math", description: "Social math problem-solving" },
  { name: "Club Tennis", description: "Competitive collegiate tennis" },
  { name: "Coffee Club @ GT", description: "Coffee tasting and brewing" },
  { name: "Consult Your Community", description: "Pro bono consulting for small businesses" },
  { name: "Cricket Club", description: "Recreational and competitive cricket" },
  { name: "Cubing Club @ GT", description: "Rubik's Cube and puzzle solving" },
  { name: "Dance Company", description: "Multi-style dance performances" },
  { name: "DanceTech", description: "Student dance showcases" },
  { name: "Data Science at GT", description: "Data science projects and bootcamps" },
  { name: "Debate Team", description: "Competitive policy and parliamentary debate" },
  { name: "Dungeons & Dragons Club", description: "Tabletop role-playing games" },
  { name: "Economics Club", description: "Economic discussions and events" },
  { name: "Engineers Without Borders", description: "Engineering solutions for global communities" },
  { name: "Entrepreneurship Club", description: "Startup ideation and growth" },
  { name: "Esports", description: "Casual and competitive gaming" },
  { name: "Figure Skating Club", description: "Recreational and competitive skating" },
  { name: "Film / Buzz Studios", description: "Student filmmaking" },
  { name: "Flash Mob @ GT", description: "Pop-up dance performances" },
  { name: "Girls Who Code", description: "Coding outreach for young students" },
  { name: "GreyHat", description: "Cybersecurity education and competitions" },
  { name: "GT Motorsports", description: "Formula-style race car engineering" },
  { name: "Hacky Sack at GT", description: "Freestyle footbag play" },
  { name: "HexLabs", description: "Hackathons and CS education" },
  { name: "Hillel", description: "Jewish student life" },
  { name: "Ice Hockey Club", description: "Competitive collegiate hockey" },
  { name: "Invention Studio", description: "Student-run makerspace" },
  { name: "iOS Club @ GT", description: "Apple app development" },
  { name: "Juggling Club", description: "Skill-based juggling" },
  { name: "Magic: The Gathering Club", description: "Card game play" },
  { name: "Meditation Club", description: "Guided meditation and mindfulness" },
  { name: "Mock Trial", description: "Competitive legal simulations" },
  { name: "Motorcycle Club", description: "Riding safety and community" },
  { name: "Origami Club", description: "Paper folding art and engineering" },
  { name: "Outdoor Recreation", description: "Adventure trips and outdoor skills" },
  { name: "Period Project @ GT", description: "Menstrual equity advocacy" },
  { name: "Robotics / Marine Robotics", description: "Autonomous vehicle development" },
  { name: "Ramblin' Reck Club", description: "Preserves GT traditions and cares for the Ramblin' Reck" },
  { name: "Ramblin' Rocket Club", description: "Competitive rocketry and high-altitude projects" },
  { name: "Ramblin' Roundnet", description: "Recreational and competitive Spikeball" },
  { name: "Real Estate at Georgia Tech", description: "Real estate education, networking, and site tours" },
  { name: "Reformed University Fellowship", description: "Christian fellowship and discussion community" },
  { name: "Regeneration Club at GT", description: "Hands-on ecological and social regeneration projects" },
  { name: "Remote Area Medical at GT", description: "Mobile clinics providing free medical services" },
  { name: "Rescue Paws USA", description: "Animal rescue advocacy and volunteering" },
  { name: "Research Insights Club", description: "Guidance on navigating academic research" },
  { name: "Residence Hall Association", description: "Student leadership and programming for on-campus housing" },
  { name: "Rise and Run", description: "Inclusive running community for neurodiverse students" },
  { name: "RoboGrads", description: "Robotics community for graduate students" },
  { name: "RoboJackets", description: "Competitive robotics teams and outreach" },
  { name: "RoboRambler", description: "RoboMaster competition robotics team" },
  { name: "Robotics Outreach Club", description: "Mentoring and volunteering with robotics teams" },
  { name: "Roller Hockey", description: "Recreational and intercollegiate roller hockey" },
  { name: "Rooted Christian Fellowship", description: "Christian speakers, discussion, and community" },
  { name: "RotorJackets", description: "FPV drone flying, racing, and training" },
  { name: "Rowing Club", description: "Competitive and recreational rowing" },
  { name: "Runnin' Wreck", description: "Social and competitive running club" },
  { name: "Sai Young Adults", description: "Interfaith spiritual discussion group" },
  { name: "Sailing Club", description: "Recreational and competitive sailing" },
  { name: "Scheller Marketing Association", description: "Marketing skills and professional development" },
  { name: "Scheller Pride", description: "LGBTQIA+ graduate community at Scheller" },
  { name: "Scholars of Finance", description: "Finance leadership and ethics organization" },
  { name: "Science & Technology Policy Connections", description: "Student-driven science and tech policy work" },
  { name: "Science Olympiad", description: "Volunteering and tournament support" },
  { name: "Seek Discomfort Club", description: "Personal growth through challenges and service" },
  { name: "Sending Smiles", description: "Letters of encouragement for cancer patients" },
  { name: "Sewa at GT", description: "Service projects rooted in selfless service" },
  { name: "Sewing & Quilting Club @ Tech", description: "Sewing, embroidery, and fiber arts" },
  { name: "Shop With a Jacket", description: "Holiday gift shopping with underserved students" },
  { name: "SiliconJackets", description: "Silicon hardware design education" },
  { name: "Skateboarding Club", description: "Group skating and skill development" },
  { name: "Ski & Snowboard Club", description: "Recreational and competitive winter sports" },
  { name: "SKY Campus Happiness", description: "Mental health, mindfulness, and resilience" },
  { name: "Smash Jackets", description: "Super Smash Bros. competitive and casual play" },
  { name: "SMILE", description: "Campus positivity and encouragement initiatives" },
  { name: "Society of Furries", description: "Social and creative furry fandom community" },
  { name: "Society of Physics Students", description: "Physics community and outreach" },
  { name: "Society of Plastics Engineers", description: "Polymer science and engineering networking" },
  { name: "Society of Women Engineers", description: "Support and advocacy for women in engineering" },
  { name: "Society of Women in Business", description: "Women's professional development in business" },
  { name: "Society of Women in Physics", description: "Supporting women in physics" },
  { name: "Solar Decathlon", description: "Sustainable building design competition" },
  { name: "Solar Racing", description: "Design and race solar-powered vehicles" },
  { name: "SOON Movement", description: "Interdenominational Christian ministry" },
  { name: "SPARK Together", description: "Compassionate leadership and service" },
  { name: "Special Pops at GT", description: "Tennis instruction for neurodiverse populations" },
  { name: "Sport Parachute Club", description: "Skydiving training and competition" },
  { name: "Sports Business Club", description: "Careers and networking in sports industry" },
  { name: "Squash Club @ GT", description: "Recreational squash" },
  { name: "Stand-Up Club at GT", description: "Writing and performing stand-up comedy" },
  { name: "Starter Bikes", description: "Bike co-op and repair space" },
  { name: "Startup Exchange", description: "Startup building and founder community" },
  { name: "Student Affiliates of ACS", description: "Chemistry community and outreach" },
  { name: "Student Cancer Coalition", description: "Cancer awareness and advocacy" },
  { name: "Student Construction Association", description: "Construction industry education" },
  { name: "Student Hospital Connections", description: "Clinical exposure for pre-health students" },
  { name: "Student Neuroscience Association", description: "Neuroscience education and outreach" },
  { name: "Student Polymer Network", description: "Polymer science networking" },
  { name: "Student Veterans Association", description: "Resources and community for veterans" },
  { name: "Students for Life", description: "Pro-life advocacy organization" },
  { name: "StORM Club", description: "Meteorology education and community" },
  { name: "Students Organizing for Sustainability", description: "Sustainability activism and community garden" },
  { name: "Students Providing Aid", description: "First-aid kit preparation for developing regions" },
  { name: "Supercomputing @ GT", description: "High-performance computing education" },
  { name: "Supersonics Club at GT", description: "High-speed aircraft design" },
  { name: "Supply Chain & Logistics Organization", description: "Supply chain education and networking" },
  { name: "Support, Health, & Education for Women", description: "Women's health service and education" },
  { name: "Survivor Club at GT", description: "Reality-show-style competitive game" },
  { name: "Swifties at GT", description: "Taylor Swift fan community" },
  { name: "Swim Club", description: "Competitive and recreational swimming" },
  { name: "Swing Dance Social Community", description: "Swing dance lessons and socials" },
  { name: "SynapseX", description: "Brain-computer interface development" },
  { name: "Table Tennis Association", description: "Recreational and competitive table tennis" },
  { name: "Tae Kwon Do", description: "Martial arts training" },
  { name: "TEAM Buzz", description: "Community service coordination" },
  { name: "Tech Pottery", description: "Pottery and ceramics community" },
  { name: "Technology Consulting Group @ GT", description: "Tech-business consulting projects" },
  { name: "Teddy Bear Hospital", description: "Reducing medical anxiety in children" },
  { name: "TEDxGeorgiaTech", description: "Student-run TEDx conference" },
  { name: "Tekstyles", description: "Hip-hop dance community" },
  { name: "The After Dark Project", description: "Humanistic medicine and reflection" },
  { name: "The Diabetes Link", description: "Support for students with Type 1 diabetes" },
  { name: "The Helping Hive", description: "Free virtual academic tutoring" },
  { name: "The Leukemia & Lymphoma Society @ GT", description: "Cancer research fundraising" },
  { name: "The Living Room", description: "Christian fellowship and weekly dinners" },
  { name: "The Navigators", description: "Nondenominational Christian ministry" },
  { name: "The Neurodiversity Initiative", description: "Advocacy and support for neurodiverse families" },
  { name: "The Nourish Project", description: "Elder care and social connection" },
  { name: "The Oasis", description: "Christian outreach community" },
  { name: "The Technique", description: "Student-run campus newspaper" },
  { name: "The Tower Research Journal", description: "Undergraduate research publication" },
  { name: "The Wesley Foundation", description: "Methodist campus ministry" },
  { name: "The Women's Network", description: "Professional growth and networking for women" },
  { name: "Theme Park Engineering & Design Club", description: "Theme park design and industry exposure" },
  { name: "Thomistic Institute @ GT", description: "Philosophy and theology discussions" },
  { name: "Tikkun Olam Makers", description: "Assistive technology projects" },
  { name: "Trading at Georgia Tech", description: "Quantitative finance education" },
  { name: "Trailblazers", description: "Outdoor service and recreation" },
  { name: "Transfer Student Association", description: "Support for transfer students" },
  { name: "Treble Choir", description: "Treble-voice choral ensemble" },
  { name: "Triathlon Club", description: "Competitive triathlon training" },

];